trainer:
  batch_size: 64
  global_seed: 0
  image_size: 128
  n_epochs: 150001
  data_path: "ds_bridge/training/annotation"
  eval_save_real: "results/Bridge/DiTTrainerScene/real/epoch"
  eval_save_gen: "results/Bridge/DiTTrainerScene/gen/epoch"
  learning_rate: 0.0001
  weight_decay: 0
  cuda_num: 0
  wandb_log: false
  val_num: 5
  val_num_gen: 10000
  gradient_accumulation_steps: 1

model:
  type: "LinearDiTActionSeqISim" #DiTActionSeqISim, DiTActionSeqFrameAtt, LinearDiTActionSeqISim, DiTActionSeqJoint
  input_size: 16
  patch_size: 2
  in_channels: 4
  hidden_size: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  action_dim: 7
  learn_sigma: false
  seq_len: 10
  mask_n: 2
  attention_mode: "linear"

diffusion:
  sample_method: "PNDM"
  scheduler_path: "pretrained_diff_models/scheduler"
  timestep_respacing: ""
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"
  variance_type: "learned_range"
  infer_num_sampling_steps: 50
  guidance_scale: 1.0
vae:
  path: "stabilityai/stable-diffusion-xl-refiner-1.0"
  subfolder: "vae"

distributed:
  backend: "nccl"
  world_size: 4  # Adjust according to the number of GPUs

wandb:
  project: "DiT Robot Image Prediction"
  entity: "nicorp96"