trainer:
  batch_size: 64
  global_seed: 0
  image_size: 256
  n_epochs: 150001
  data_path: "ds_bridge/training/annotation"
  eval_save_real: "results/Bridge/DiTTrainerSceneMC/real/epoch"
  eval_save_gen: "results/Bridge/DiTTrainerSceneMC/gen/epoch"
  learning_rate: 0.0001
  weight_decay: 0
  cuda_num: 0
  wandb_log: false
  val_num: 5000

model:
  type: "DiT"
  input_size: 32
  patch_size: 2
  in_channels: 4
  hidden_size: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  action_dim: 7
  learn_sigma: false
  seq_len: 10
  mask_n: 2

diffusion:
  timestep_respacing: ""

vae:
  path: "stabilityai/stable-diffusion-xl-refiner-1.0"
  subfolder: "vae"

distributed:
  backend: "nccl"
  world_size: 1  # Adjust according to the number of GPUs

wandb:
  project: "DiT Robot Image Prediction"
  entity: "nicorp96"